# Generated by Django 5.2.12 on 2026-03-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_academy', '0002_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
