# Generated by Django 5.2.12 on 2026-03-18 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_academy', '0006_lessonprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='date_enrolled',
            new_name='enrolled_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='live_link',
        ),
        migrations.RemoveField(
            model_name='course',
            name='video_url',
        ),
        migrations.AddField(
            model_name='course',
            name='live_lecture_link',
            field=models.URLField(blank=True, help_text='Zoom/Meet link for live session', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default='default_course.jpg', upload_to='course_thumbs/'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='Optional lesson notes'),
        ),
        migrations.AddField(
            model_name='user',
            name='enrollment_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=1, help_text='Sequence (1, 2, 3...)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(help_text='YouTube Embed Link for VOD'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option4',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_text',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
    ]
