# Generated by Django 5.2.12 on 2026-03-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_academy', '0007_rename_date_enrolled_enrollment_enrolled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='live_lecture_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
    ]
